services:
  cassandra:
    image: cassandra:latest
    container_name: cassandra
    ports:
      - "9042:9042"
    environment:
      CASSANDRA_CLUSTER_NAME: "MyCluster"
      CASSANDRA_NUM_TOKENS: 256
      CASSANDRA_DC: "datacenter1"
      CASSANDRA_RACK: "rack1"
      CASSANDRA_SEEDS: "cassandra"
    networks:
      - app-network

#  scylla:
#    image: scylladb/scylla:latest
#    container_name: scylla
#    ports:
#      - "9142:9142"
#    environment:
#      SCYLLA_CLUSTER_NAME: "MyScyllaCluster"
#      SCYLLA_NUM_TOKENS: 256
#      SCYLLA_SEEDS: "scylla"
#      SCYLLA_DC: "datacenter1"
#      SCYLLA_RACK: "rack1"

  app:
    build: .
    container_name: eventflux
    environment:
      CASSANDRA_HOST: cassandra
      SCYLLA_HOST: scylla
      APP_HOST: 0.0.0.0
      APP_PORT: 8080
    ports:
      - "8080:8080"
    depends_on:
      - cassandra
      - scylla
    networks:
      - app-network

networks:
  app-network:
    driver: bridge